language: ruby
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails3-0
  - gemfiles/Gemfile.rails3-2
  - gemfiles/Gemfile.rails4-0
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails4-0
  allow_failures:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails4-0
